version: 2

jobs:

  test-zshrc:
    docker:
      - image: "opensuse:tumbleweed"
    steps:
      - checkout
      - run:
          name: Install zshrc profile
          command: cp zshrc ~/.zshrc
      - run:
          name: Install dependencies
          command: zypper in -y git zsh which
      - run:
          name: Install zplug
          command: |
            git clone https://github.com/zplug/zplug ~/.zplug
      - run:
          name: Test out zshrc
          shell: /usr/bin/zsh
          command: |
            export SHELL=/bin/zsh
            export TERM="xterm-256color"
            . ~/.zshrc


workflows:
  version: 2
  test:
    jobs:
      - test-zshrc
